### ISSUE TITLE
Stickies that aren't the Weekly Sticky are un-stickied on accident

### ISSUE THREAD

**Issue by dmargol1** [datascience-bot/datascience-bot#57]

**Comment by vogt4nick** [comment]
I need to research how a new sticky chooses which one to replace. I get the feeling that replacing a specific sticky should be easy to implement.

Related, but not root cause: For a short period, [two entering & transitioning threads are stickied](https://github.com/datascience-bot/datascience-bot/blob/656bce6b7facae832b7e15d17236b64aa9e12d61/libs/entering_and_transitioning_app/__init__.py#L248-L256).

**Comment by vogt4nick** [comment]
So looks like we already were replacing the bottom sticky:

```
submission.mod.sticky(state=True, bottom=True)
```

It's possible (I'm not sure) that the "top" sticky is always the oldest. That means any post stickied between Entering & Transitioning threads becomes the "bottom" sticky, and is then replaced. 

Anyway we can fix this by just unstickying the old thread before stickying the new one.
